### ISSUE TITLE
Datasource options not being applied

### ISSUE THREAD

**Issue by jkknorr** [ansible-middleware/ansible_collections_jcliff#50]
I'm finding that not all the fields specified within a datasource component are being set in the WildFly XML.  From this Ansible code:

       - name: fooDS
          jta: "true"
          pool_name: fooDS
          jndi_name: java:jboss/datasources/fooDS
          use_java_context: "false"
          connection_url: jdbc:oracle:thin:@{{dbhost}}:16709:q722
          driver_name: oracle
          enabled: "true"
          password: "{{ datasource_pw }}"
          user_name: FOO_GUSER
          max_pool_size: "10"
          min_pool_size: "30"
          idle_timeout_minutes: "20"
          query_timeout: "60000"
          check_valid_connection_sql: SELECT 1 FROM DUAL
          validate_on_match: "false"

I get this XML:

```
  <datasource jndi-name="java:jboss/datasources/fooDS" pool-name="fooDS" use-java-context="false">
                    <connection-url>jdbc:oracle:thin:@foo.example.com:16709:q722</connection-url>
                    <driver>oracle</driver>
                    <security>
                        <user-name>FOO_GUSER</user-name>
                        <password>**************</password>
                    </security>
                </datasource>
```

Digging into datasource.j2:

```
{ "datasource" => {
  "{{ values['name'] }}" => {
    {% if 'pool_name' in values %} "pool-name" => "{{ values['pool_name'] }}", {% endif %}
    "connection-url" => "{{ values['connection_url'] }}",
    "driver-name" => "{{ values['driver_name'] }}",
    "jndi-name" => "{{ values['jndi_name'] }}",
    {% if 'password' in values %} "password" => "{{ values['password'] }}", {% endif %}
    {% if 'user_name' in values %} "user-name" => "{{ values['user_name'] }}", {% endif %}
    {% if 'enabled' in values %} "enabled" => "{{ values['enabled'] }}", {% endif %}
    {% if 'use_java_context' in values %} "use-java-context" => "{{ values['use_java_context'] }}" {% endif %}
   }
 }
}
```
It looks like the fields I'm missing are not being handled as part of the template.  Is this a WIP that isn't labeled as such?

**Comment by sabre1041** [comment]
@jkknorr you are correct that not every property is considered and is one of the current shortcomings.

https://github.com/wildfly-extras/ansible_collections_jcliff/pull/47 attempts to introduce a new, more dynamic method of managing resources

**Comment by rpelisse** [comment]
We are no longer using JCliff to configure Wildfly, so I'm closing this issue.
